CREATE TABLE IF NOT EXISTS public."eventActivities" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    event_id BIGINT NOT NULL REFERENCES public.events (id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    start_time_local TIMESTAMPTZ NOT NULL,
    end_time_local TIMESTAMPTZ,
    timezone TEXT NOT NULL DEFAULT 'America/Chicago',
    location_name TEXT NOT NULL,
    speakers TEXT NOT NULL DEFAULT '',
    activity_type TEXT NOT NULL,
    room_capacity INTEGER NOT NULL DEFAULT 0,
    registered_users INTEGER NOT NULL DEFAULT 0,
    scanned_in_users INTEGER NOT NULL DEFAULT 0,
    queue_length INTEGER NOT NULL DEFAULT 0,
    source TEXT NOT NULL DEFAULT 'seeded',
    created_by_display TEXT
);

ALTER TABLE public."eventActivities"
    ADD COLUMN IF NOT EXISTS room_capacity INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS registered_users INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS scanned_in_users INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS queue_length INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS eventactivities_unique_seed
    ON public."eventActivities"(event_id, title, start_time_local);

ALTER TABLE public."eventActivities" ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'eventActivities'
          AND policyname = 'eventActivities_select_anon'
    ) THEN
        CREATE POLICY "eventActivities_select_anon"
            ON public."eventActivities"
            FOR SELECT
            TO anon, authenticated
            USING (true);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'eventActivities'
          AND policyname = 'eventActivities_insert_anon'
    ) THEN
        CREATE POLICY "eventActivities_insert_anon"
            ON public."eventActivities"
            FOR INSERT
            TO anon, authenticated
            WITH CHECK (true);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'eventActivities'
          AND policyname = 'eventActivities_update_anon'
    ) THEN
        CREATE POLICY "eventActivities_update_anon"
            ON public."eventActivities"
            FOR UPDATE
            TO anon, authenticated
            USING (true)
            WITH CHECK (true);
    END IF;
END
$$;

INSERT INTO public."eventActivities" (
    event_id,
    title,
    description,
    start_time_local,
    end_time_local,
    timezone,
    location_name,
    speakers,
    activity_type,
    room_capacity,
    registered_users,
    scanned_in_users,
    queue_length,
    source,
    created_by_display
)
VALUES
    (
        1,
        'Vibe Coding from Idea to MVP at Warp Speed',
        'Hands-on workshop demonstrating rapid product planning and prototyping workflows.',
        '2026-03-14 11:00:00-05',
        '2026-03-14 12:00:00-05',
        'America/Chicago',
        'Austin Convention Center - Room 18AB',
        'Matthew Steiner, Guest Facilitators',
        'Workshop',
        80,
        62,
        21,
        0,
        'seeded',
        NULL
    ),
    (
        1,
        'SXSW Opening Keynote: AI + Creativity',
        'Main keynote exploring practical AI adoption for creators, founders, and teams.',
        '2026-03-14 09:00:00-05',
        '2026-03-14 10:00:00-05',
        'America/Chicago',
        'Ballroom D, Austin Convention Center',
        'SXSW Keynote Team',
        'Keynote',
        400,
        392,
        388,
        0,
        'seeded',
        NULL
    ),
    (
        1,
        'Neon Skyline: Downtown Music Showcase',
        'Evening live set featuring emerging electronic artists and local collaborations.',
        '2026-03-14 20:00:00-05',
        NULL,
        'America/Chicago',
        'Red River District Stage',
        'Various Artists',
        'Music',
        180,
        180,
        180,
        18,
        'seeded',
        NULL
    ),
    (
        1,
        'Future Frames: Indie Film Premiere',
        'Screening followed by a short Q&A with the director and production team.',
        '2026-03-15 14:30:00-05',
        '2026-03-15 16:30:00-05',
        'America/Chicago',
        'Paramount Theatre',
        'Director Panel',
        'Film',
        120,
        120,
        120,
        0,
        'seeded',
        NULL
    ),
    (
        1,
        'Moonshot Mixer: Founder + Builder Meetup',
        'Fictional networking session for demo purposes.',
        '2026-03-15 18:00:00-05',
        '2026-03-15 19:30:00-05',
        'America/Chicago',
        'The Lantern Lounge',
        'Community Hosts',
        'Networking',
        60,
        60,
        60,
        14,
        'seeded',
        NULL
    )
ON CONFLICT (event_id, title, start_time_local) DO UPDATE SET
    description = EXCLUDED.description,
    end_time_local = EXCLUDED.end_time_local,
    timezone = EXCLUDED.timezone,
    location_name = EXCLUDED.location_name,
    speakers = EXCLUDED.speakers,
    activity_type = EXCLUDED.activity_type,
    room_capacity = EXCLUDED.room_capacity,
    registered_users = EXCLUDED.registered_users,
    scanned_in_users = EXCLUDED.scanned_in_users,
    queue_length = EXCLUDED.queue_length,
    source = EXCLUDED.source;
